# Generated by Django 5.1.5 on 2026-05-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_location_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='kind',
            field=models.CharField(choices=[('course', 'Курс'), ('seminar', 'Семинар'), ('practice', 'Учебная практика')], max_length=16),
        ),
    ]
